# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181002_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Entreprise'),
        ),
    ]
