# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181005_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'devis en cours'), ('2', 'devis annul\xe9'), ('3', 'facture')], max_length=250, null=True),
        ),
    ]
