# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20181005_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(blank=True, choices=[('proceed', 'devis en cours'), ('dis', 'devis annul\xe9'), ('invoice', 'facture')], max_length=250, null=True),
        ),
    ]
