# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20181005_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'devis en cours'), ('b', 'devis annul\xe9'), ('c', 'facture')], max_length=250, null=True),
        ),
    ]
