# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20181008_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de cr\xe9ation'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='limit_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de validit\xe9/date de paiement'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'devis en cours'), (2, 'devis annul\xe9'), (3, 'facture'), (4, 'facture r\xe9gl\xe9e')], null=True),
        ),
    ]
