# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20181008_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de cr\xe9ation'),
        ),
    ]
