# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20181008_1055'),
        ('app', '0023_quotation_slug'),
    ]

    operations = [
    ]
