# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pr\xe9nom')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entreprise')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Adresse')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code Postal')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ville')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('short_desc', models.TextField(blank=True, null=True, verbose_name='En bref')),
                ('decription', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price')),
                ('ref', models.CharField(blank=True, max_length=150, null=True, verbose_name='R\xe9f\xe9rence')),
            ],
        ),
    ]
