# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.16 on 2018-10-04 13:49
=======
# Generated by Django 1.11.16 on 2018-10-04 13:52
>>>>>>> dc5b6a5effcd2f06304ad8784efbf627b2df97ed
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181004_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='T\xe9l\xe9phone'),
        ),
    ]
