# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 09:55
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_quotation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='company', unique=True, verbose_name='Slug'),
        ),
    ]
