# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181008_0745'),
        ('app', '0017_auto_20181005_1353'),
    ]

    operations = [
    ]
