# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20181008_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='limit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
