# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_quotation_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='creation_date',
        ),
    ]
